name: Compile and Commit documentation file.
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create fonts directory in the repository
        run: mkdir -p $GITHUB_WORKSPACE/fonts

      - name: Download and Extract Fonts
        run: |
          wget -P $GITHUB_WORKSPACE/fonts https://github.com/tonsky/FiraCode/releases/download/5.2/Fira_Code_v5.2.zip
          unzip $GITHUB_WORKSPACE/fonts/Fira_Code_v5.2.zip -d $GITHUB_WORKSPACE/fonts/firacode
          wget -P $GITHUB_WORKSPACE/fonts https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifCJKjp-hinted.zip
          unzip $GITHUB_WORKSPACE/fonts/NotoSerifCJKjp-hinted.zip -d $GITHUB_WORKSPACE/fonts/notoserifcjkjp
          wget -P $GITHUB_WORKSPACE/fonts https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMonoCJKjp-hinted.zip
          unzip $GITHUB_WORKSPACE/fonts/NotoSansMonoCJKjp-hinted.zip -d $GITHUB_WORKSPACE/fonts/notosansmono

      - name: Compile Typst to PDF
        uses: ammar-ahmed22/compile-typst-action@v1
        with:
          source_paths: 'docs/doc.typ'
          output_paths: 'docs/doc.pdf'
          fonts_path: $GITHUB_WORKSPACE/fonts

      - name: Remove Fonts from Repository
        run: rm -rf $GITHUB_WORKSPACE/fonts

      - name: Commit compiled PDFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[continuous deployment]: Compiled docs to PDF'
          file_pattern: 'docs/doc.pdf'
